# Generated by Django 2.2.2 on 2021-09-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('index', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('num_sections', models.IntegerField()),
                ('num_segments', models.IntegerField()),
                ('song_class', models.IntegerField()),
                ('num_bars', models.IntegerField()),
                ('start_ratings', models.IntegerField()),
            ],
        ),
    ]
