# Generated by Django 2.2.2 on 2021-09-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='start_ratings',
            new_name='star_ratings',
        ),
    ]
